In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pls
import torch

In [2]:
torch.range(0, 19)

/var/folders/4t/k648lnt161n8zjprt2d7p8d00000gn/T/ipykernel_10269/498835477.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 19)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19.])

In [3]:
torch.__version__

'2.1.1'

In [4]:
oneto_seven = torch.arange(1, 7, 2, dtype=torch.float32)

In [5]:
torch.zeros_like(input=oneto_seven)

tensor([0., 0., 0.])

In [6]:
oneto_seven.dtype

torch.float32

In [7]:
torch.tensor([1,2,3.646], dtype=torch.int32) * torch.arange(1, 7, 2, dtype=torch.float16)

tensor([ 1.,  6., 15.], dtype=torch.float16)

In [8]:
testtensor = torch.rand(3, 4)

In [9]:
testtensor.shape

torch.Size([3, 4])

In [10]:
testtensor.size()

torch.Size([3, 4])

In [11]:
testtensor.device

device(type='cpu')

In [12]:
testtensor

tensor([[0.2755, 0.8590, 0.1628, 0.5936],
        [0.9090, 0.0900, 0.1327, 0.2330],
        [0.6693, 0.7393, 0.2337, 0.5752]])

In [13]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [14]:
tensor + 100

tensor([101, 102, 103])

In [15]:
torch.rand(2, 3).matmul(torch.rand(3, 2))

tensor([[0.8670, 0.4118],
        [0.3882, 0.1541]])

In [16]:
torch.rand(2, 3)

tensor([[0.3702, 0.5042, 0.3063],
        [0.8164, 0.9994, 0.0831]])

In [17]:
x = torch.rand(10,2)
x

tensor([[0.7177, 0.3891],
        [0.5473, 0.5235],
        [0.1151, 0.8591],
        [0.0412, 0.9774],
        [0.8991, 0.5809],
        [0.8403, 0.2340],
        [0.7386, 0.0789],
        [0.6776, 0.6162],
        [0.4628, 0.9828],
        [0.6334, 0.8153]])

In [18]:
x.argmin()

tensor(6)

In [19]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [20]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [21]:
x.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [22]:
# change z change x, view share the same memory of origin
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [23]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [24]:
x = torch.rand(1,2,1)
x

tensor([[[0.0946],
         [0.5386]]])

In [25]:
x.squeeze().squeeze()

tensor([0.0946, 0.5386])

In [26]:
torch.permute(x, (1,0,2))

tensor([[[0.0946]],

        [[0.5386]]])

In [27]:
torch.device("mps")

device(type='mps')

In [28]:
import torch
a = torch.rand(3,5)
print(a)
b = torch.device('mps')
print(b)

tensor([[0.1424, 0.2473, 0.7569, 0.4553, 0.8631],
        [0.9082, 0.1423, 0.4760, 0.3186, 0.6776],
        [0.9543, 0.0465, 0.6475, 0.6635, 0.4647]])
mps


In [29]:
device = "mps"
device

'mps'

In [30]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [31]:
tensor_mps = torch.tensor([1,2,3], device="mps")
print(tensor_mps, tensor_mps.device)

tensor([1, 2, 3], device='mps:0') mps:0


In [32]:
tensor_mps.cpu().numpy()

array([1, 2, 3])

In [33]:
import torch
torch.__version__

'2.1.1'

In [34]:
torch.tensor([[1,1],[2,2]])

tensor([[1, 1],
        [2, 2]])

In [4]:
torch.tensor(1)

tensor(1)

In [6]:
torch.rand(2,2)

tensor([[0.5698, 0.3208],
        [0.7051, 0.4723]])

In [8]:
torch.ones(size=(3,2)).dtype

torch.float32

In [9]:
torch.arange(start = 0, end = 10, step = 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
torch.zeros_like(torch.zeros(size = (3, 3)))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
1