In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pls
import torch

In [3]:
torch.range(0, 19)

/var/folders/4t/k648lnt161n8zjprt2d7p8d00000gn/T/ipykernel_40010/498835477.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 19)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19.])

In [4]:
torch.__version__

'2.1.1'

In [15]:
oneto_seven = torch.arange(1, 7, 2, dtype=torch.float32)

In [16]:
torch.zeros_like(input=oneto_seven)

tensor([0., 0., 0.])

In [17]:
oneto_seven.dtype

torch.float32

In [22]:
torch.tensor([1,2,3.646], dtype=torch.int32) * torch.arange(1, 7, 2, dtype=torch.float16)

tensor([ 1.,  6., 15.], dtype=torch.float16)

In [32]:
testtensor = torch.rand(3, 4)

In [33]:
testtensor.shape

torch.Size([3, 4])

In [34]:
testtensor.size()

torch.Size([3, 4])

In [35]:
testtensor.device

device(type='cpu')

In [36]:
testtensor

tensor([[0.9802, 0.8301, 0.3622, 0.4881],
        [0.5973, 0.7674, 0.3391, 0.3021],
        [0.5837, 0.3873, 0.1701, 0.1268]])

In [37]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor + 100

tensor([101, 102, 103])

In [50]:
torch.rand(2, 3).matmul(torch.rand(3, 2))

tensor([[0.7254, 0.6180],
        [0.4104, 0.4406]])

In [48]:
torch.rand(2, 3)

tensor([[0.3214, 0.9094, 0.7104],
        [0.7880, 0.3127, 0.5861]])

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 9.06 µs


In [57]:
x = torch.rand(10,2)
x

tensor([[0.8017, 0.0229],
        [0.5446, 0.2342],
        [0.9304, 0.2754],
        [0.7049, 0.2904],
        [0.0730, 0.5617],
        [0.5971, 0.2691],
        [0.8812, 0.1871],
        [0.3319, 0.7649],
        [0.1481, 0.2244],
        [0.9319, 0.3174]])

In [58]:
x.argmin()

tensor(1)