In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pls
import torch

In [3]:
torch.range(0, 19)

/var/folders/4t/k648lnt161n8zjprt2d7p8d00000gn/T/ipykernel_40010/498835477.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 19)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19.])

In [4]:
torch.__version__

'2.1.1'

In [15]:
oneto_seven = torch.arange(1, 7, 2, dtype=torch.float32)

In [16]:
torch.zeros_like(input=oneto_seven)

tensor([0., 0., 0.])

In [17]:
oneto_seven.dtype

torch.float32

In [22]:
torch.tensor([1,2,3.646], dtype=torch.int32) * torch.arange(1, 7, 2, dtype=torch.float16)

tensor([ 1.,  6., 15.], dtype=torch.float16)

In [32]:
testtensor = torch.rand(3, 4)

In [33]:
testtensor.shape

torch.Size([3, 4])

In [34]:
testtensor.size()

torch.Size([3, 4])

In [35]:
testtensor.device

device(type='cpu')

In [36]:
testtensor

tensor([[0.9802, 0.8301, 0.3622, 0.4881],
        [0.5973, 0.7674, 0.3391, 0.3021],
        [0.5837, 0.3873, 0.1701, 0.1268]])

In [37]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor + 100

tensor([101, 102, 103])

In [50]:
torch.rand(2, 3).matmul(torch.rand(3, 2))

tensor([[0.7254, 0.6180],
        [0.4104, 0.4406]])

In [48]:
torch.rand(2, 3)

tensor([[0.3214, 0.9094, 0.7104],
        [0.7880, 0.3127, 0.5861]])

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 9.06 µs


In [57]:
x = torch.rand(10,2)
x

tensor([[0.8017, 0.0229],
        [0.5446, 0.2342],
        [0.9304, 0.2754],
        [0.7049, 0.2904],
        [0.0730, 0.5617],
        [0.5971, 0.2691],
        [0.8812, 0.1871],
        [0.3319, 0.7649],
        [0.1481, 0.2244],
        [0.9319, 0.3174]])

In [58]:
x.argmin()

tensor(1)

In [61]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [65]:
x.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [67]:
# change z change x, view share the same memory of origin
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [70]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [82]:
x = torch.rand(1,2,1)
x

tensor([[[0.0636],
         [0.7241]]])

In [83]:
x.squeeze().squeeze()

tensor([0.0636, 0.7241])

In [89]:
torch.permute(x, (1,0,2))

tensor([[[0.0636]],

        [[0.7241]]])

In [5]:
torch.device("mps")

device(type='mps')

In [6]:
import torch
a = torch.rand(3,5)
print(a)
b = torch.device('mps')
print(b)

tensor([[0.9209, 0.9656, 0.3207, 0.9572, 0.8675],
        [0.4760, 0.4830, 0.6711, 0.2451, 0.0056],
        [0.1955, 0.6968, 0.0681, 0.9563, 0.4052]])
mps


In [9]:
device = "mps"
device

'mps'

In [13]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [14]:
tensor_mps = torch.tensor([1,2,3], device="mps")
print(tensor_mps, tensor_mps.device)

tensor([1, 2, 3], device='mps:0') mps:0


In [20]:
tensor_mps.cpu().numpy()

array([1, 2, 3])

In [1]:
import torch
torch.__version__

'2.1.1'

In [3]:
torch.tensor([[1,1],[2,2]])

tensor([[1, 1],
        [2, 2]])

In [4]:
torch.tensor(1)

tensor(1)

In [6]:
torch.rand(2,2)

tensor([[0.5698, 0.3208],
        [0.7051, 0.4723]])

In [8]:
torch.ones(size=(3,2)).dtype

torch.float32

In [9]:
torch.arange(start = 0, end = 10, step = 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
torch.zeros_like(torch.zeros(size = (3, 3)))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
