# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
ans = torch.rand(size=(7,7))
ans


tensor([[0.1791, 0.9629, 0.2449, 0.0322, 0.7803, 0.7551, 0.2483],
        [0.6146, 0.6610, 0.0325, 0.9374, 0.9177, 0.6611, 0.9574],
        [0.0016, 0.8347, 0.0346, 0.7903, 0.7031, 0.7817, 0.2208],
        [0.3487, 0.0904, 0.8619, 0.0967, 0.7865, 0.7836, 0.7464],
        [0.6041, 0.4813, 0.0971, 0.5114, 0.6320, 0.5781, 0.3718],
        [0.0533, 0.7915, 0.2908, 0.7923, 0.2193, 0.7384, 0.7366],
        [0.3481, 0.8342, 0.9212, 0.5718, 0.1793, 0.9868, 0.9044]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
another_rand = torch.rand(size=(1, 7))
# Perform matrix multiplication 
new_ans = ans.matmul(another_rand.T)
new_ans


tensor([[1.6310],
        [2.4117],
        [1.7054],
        [2.0417],
        [1.5539],
        [1.8415],
        [2.3564]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
rand1 = torch.rand(size=(7,7))
rand2 = torch.rand(size=(1,7))


# Matrix multiply tensors
rand1.matmul(rand2.T)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.mps.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed

torch.manual_seed(1234)

# Check for access to GPU
torch.mps

# Create two random tensors on GPU
rand1 = torch.rand(size=(2, 3)).to("mps")
rand2 = torch.rand(size=(2, 3)).to("mps")
rand1.device, rand1, rand2

(device(type='mps', index=0),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [17]:
# Perform matmul on tensor_A and tensor_B
ans_7 = rand1.matmul(rand2.T)
rand1.matmul(rand2.T), rand1.matmul(rand2.T).shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='mps:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max
print(ans_7.max())
# Find min
print(ans_7.min())


tensor(0.5617, device='mps:0')
tensor(0.3647, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
# Find arg max

print(ans_7.argmax())
# Find arg min
print(ans_7.argmin())


tensor(3, device='mps:0')
tensor(0, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand(size=(1, 1, 1, 7))


# Remove single dimensions
rand_tensor_squeeze = rand_tensor.squeeze()



# Print out tensors and their shapes
rand_tensor, rand_tensor.shape, rand_tensor_squeeze, rand_tensor_squeeze.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]]]]),
 torch.Size([1, 1, 1, 7]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]),
 torch.Size([7]))